# Actions train a model on Azure Machine Learning
name: aml-deploy-workflow

on:
  workflow_dispatch:
    inputs:
      issue_id:
        description: 'GitHub Issue ID to comment'     
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
        
    # Connect or Create the Azure Machine Learning Workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy model in Azure Machine Learning to ACI
    - name: Deploy model
      id: aml_deploy
      uses: Azure/aml-deploy@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          model_name: mlops-example-master
          model_version: 2

    # Create Comment
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.inputs.issue_id }}
        token: ${{ secrets.BOT_TOKEN }}
        body: |
          ### Azure ML Studio Alert

          ** 🛫 Deploy Result**  
          - **Endpoint:** ${{ steps.aml_deploy.outputs.service_scoring_uri }}
          - **Swagger:** ${{ steps.aml_deploy.outputs.service_swagger_uri }}
